### PR TITLE
For cmssw 74 x bugfixes to patana step

### PR DESCRIPTION
**Pull request by dildick**
Producers are defined here:
https://github.com/cms-tamu/MuJetAnalysis/blob/for-CMSSW-74X/MuJetProducer/python/MuJetProducer_cff.py

Baseline analyzer: 
https://github.com/cms-tamu/MuJetAnalysis/blob/for-CMSSW-74X/CutFlowAnalyzer/python/CutFlowAnalyzer_cfi.py

Cutflow analyzers are defined here:
https://github.com/cms-tamu/MuJetAnalysis/blob/for-CMSSW-74X/CutFlowAnalyzer/python/CutFlowAnalyzer_cff.py

### CODE REVIEW

**Comment by dildick** [comment]
@bmichlin @castaned @jrorie @lpernie

**Comment by bmichlin** [comment]
All print statements still in place for debugging.

**Comment by dildick** [comment]
What do you mean? You want to get rid of them?

**Comment by bmichlin** [comment]
Github acted strangely while I was committing my changes.  I will revert to my previous commit and retry.

**Pull request merged**
