### PR TITLE
Complementary fix to the sameTrack function fix in PR #35

### PR DESCRIPTION
**Pull request by weishi10141993**
slide 23-24: https://github.com/weishi10141993/DarkSector/blob/master/Proposal_Solution_MiniAOD_precision_problem.pdf
Complementary fix to PR #35

### CODE REVIEW

**Comment by weishi10141993** [comment]
@lpernie, could you review and merge?

Wei

**Comment by dildick** [comment]
why not put these updates in a branch for 10_2_X? 9XY is already superseded for run-2 analyses

**Comment by weishi10141993** [comment]
No, don't open a new branch again. I want them to be in the same branch for now. 'for-CMSSW-92X' is fine. It's just a name.

Wei

**Comment by lpernie** [comment]
Ok I will merge, but please let' try to create a new definitive new branch. 10_2_0 will be deployed at T0 tomorrow, and the validation presented today looks fine

**Pull request merged**
